workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Build
        script: |
          xcodebuild \
          -project BirthdayApp.xcodeproj \
          -scheme BirthdayApp \
          -sdk iphoneos \
          -configuration Release \
          build
    artifacts:
      - build/**/*.ipa
