workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          echo "No dependencies"

      - name: Build IPA
        script: |
          xcodebuild -project ExampleMVVM.xcodeproj \
          -scheme ExampleMVVM \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath build/Runner.xcarchive

          xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath build/

    artifacts:
      - build/**/*.ipa
